export { default as NavBar } from './NavBar/NavBar'
export { default as MainSerie } from './MainSerie/MainSerie'
export { default as Slider } from './Slider/Slider'
export { default as Footer } from './Footer/Footer'
export { default as NavElement } from './NavElement/NavElement'
export { default as Technology } from './Technology/Technology'
